# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-04 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='data_fechamento_palestras',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='descrição',
            field=markdownx.models.MarkdownxField(default='teste'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='meetup_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='nome',
            field=models.CharField(default='PythOnRio', max_length=255),
        ),
        migrations.AddField(
            model_name='evento',
            name='palestras_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
