# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-04 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180204_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parceiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_url', models.URLField()),
                ('link', models.URLField()),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='evento',
            name='cidade',
            field=models.CharField(default='Riode Janeiro', max_length=255),
        ),
        migrations.AddField(
            model_name='evento',
            name='parceiros',
            field=models.ManyToManyField(blank=True, to='core.Parceiro'),
        ),
    ]
